### ISSUE TITLE
token persistence roadmap

### ISSUE THREAD

**Issue by benjiqq** [SaitoTech/saito-rust-workspace#416]
# overview
- [x] refactor work so far, remove analytics workspace and integrate in core
- [x] remove ChainRunner
- [ ] fix any issues with testmanager and make it a namespace
-  [ ] utxpdump utility in core, define the CLI
- [ ] tests for issuance
- [ ] make a tx, check balance
- [ ] make wrong tx and check they fail
- [ ] hook up to live server (tbd)
- [ ] dont use balance_map in main

# PR and issue breakdown
https://github.com/SaitoTech/saito-rust-workspace/issues/410
https://github.com/SaitoTech/saito-rust-workspace/issues/411
https://github.com/SaitoTech/saito-rust-workspace/tree/feature/blockloading

**Comment by benjiqq** [comment]
rought process, upgrade by

1. stop saito
2. run command-line executable that parses blockchain and produces utxoset dump
3. Copy that file to new issuance file
4. Restart saito
5. Confirm utxoset valid

**Comment by benjiqq** [comment]
genesis block load should be figure out in main and pass as variable
